name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  confirm-rollback:
    name: Confirm Rollback
    runs-on: ubuntu-latest
    if: always() # Run this job regardless of previous job status
    steps:
      - name: Manual Confirmation
        id: confirm
        run: |
          echo "Do you want to rollback to the previous release? (yes/no)"
          read rollback_decision
          echo "::set-output name=rollback_decision::$rollback_decision"
      - name: Rollback
        if: ${{ steps.confirm.outputs.rollback_decision == 'yes' }}
        run: |
          # Perform the rollback using Heroku CLI commands
          heroku releases:rollback -a your-heroku-app
